#!/bin/sh
set -e

error() { echo "error: $*" >&2; }
die() { error "$*"; exit 1; }
usage()
{
	: 'usage():' "$@"
	if test "$#" -gt '0'; then
		error "$*"
		echo "try 'credstash-install --help'" >&2
		exit 1
	fi
	sed -e 's/^	//'<<USAGE
	usage: credstash-install [options] <version>"
	  options:
	    -d, --debug		Enable debugging output
	    -h, --help		Display this help

USAGE
	# Requests for help are never an error
	exit 0
}

regexp()
{
        : 'regexp():' "$@"
        awk "/${1}/{exit 0;}{exit 1;}" <<EOF
${2}
EOF
}

for arg; do case "${arg}" in (-h|--help) usage;; esac;done
while test "$#" -gt '0'; do
	case "${1}" in
	(-d|--debug)	set -x;;
	(--)		shift;break;;
	(-*)		usage "unknown option '${1}'";;
	(*)		break;;
	esac
	shift 1
done

test "$#" -gt '0' || usage 'no credstash version specified'
regexp '^[0-9]+\.[0-9]+\.[0-9]+$' "${1}" || usage "invalid version '${1}'"

mkdir -p '.terraform/plugins/linux_amd64'
curl -s -o ".terraform/plugins/linux_amd64/terraform-provider-credstash_v${1}" \
	"https://github.com/sspinc/terraform-provider-credstash/releases/download/v${1}/terraform-provider-credstash_linux_amd64"
chmod 0755 ".terraform/plugins/linux_amd64/terraform-provider-credstash_v${1}"
